### ISSUE TITLE
PHP issue

### ISSUE THREAD

**Issue by bbbenji** [serveradminsh/installers#1]
As per comments in the PHP example, I have received the following results.

Default
`listen = /run/php/php7.0-fpm.sock`
results in
`failed (111: Connection refused) while connecting to upstream`
when attempting to view php file

`listen = unix:/run/php/php7.0-fpm.sock`
results in
`Job for php7.0-fpm.service failed because the control process exited with error code.`
when restarting php-fpm

`listen = 127.0.0.1:9000`
WORKS

**Comment by jonathantittle** [comment]
@bbbenji 

I apologize for the delayed response :-).

When it comes to the current installers, manual configuration and setup is still required. When using a socket connection, you'll need to update the NGINX server block to match.

So if you're using a socket in the PHP-FPM pool file, you need to set `fastcgi_pass` in the server block to reflect that, otherwise the connection will fail. Setting the correct permissions on your files and directories is also a requirement to ensure that either NGINX or PHP-FPM can properly read the files and directories.

I am working on a newer release which will handle much of the work that is currently manual, though I don't have an exact release date just yet.

**Comment by bbbenji** [comment]
Hi jonathantittle.

First off thank you for taking the time to create these scripts, they have already saved me much time and hassle.

Regarding this issue, please note`/run/php/php7.0-fpm.sock` and ` unix:/run/php/php7.0-fpm.sock` have been correctly set in both the NGINX server block as well as PHP-FPM config. The only configuration that works is `127.0.0.1:9000`.

Looking forward to updates to the scripts!
